apiVersion: v1
kind: Pod
metadata:
  name: rr-mongodb
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:bionic
    volumeMounts:
    - mountPath: "/data/db"
      name: mongo-do-volume
  initContainers:
  - name: mongodb-data-permission-fix
    image: busybox
    command: ["/bin/chmod","-R","777", "/data"]
    volumeMounts:
    - name: mongo-do-volume
      mountPath: /data
  volumes:
    - name: mongo-do-volume
      persistentVolumeClaim:
        claimName: mdb-pvc
