apiVersion: v1
kind: Pod
metadata:
  name: rr-test
  labels:
    purpose: test-rr
spec:
  containers:
  - name: rr-test-container
    image: registry.digitalocean.com/sproj/rr:latest
    command: ["sleep"]
    args: ["3600"]
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
  restartPolicy: OnFailure
